baseURL = "/"
languageCode = "en-us"
title = "CC's Sink"
theme = "hello-friend-ng"
defaultContentLanguage = "en"

enableEmoji = true
enableRobotsTXT = true

[pagination]
pagerSize = 5

[services]
  [services.googleAnalytics]
    id = "UA-36352435-4"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  dateform = "2006-01-02"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  description = "A spot for my thoughts, ramblings, and occasionally advice"
  keywords = ""
  images = [""]

  homeSubtitle = "A spot for my thoughts, ramblings, and occasionally advice"

  disableReadOtherPosts = false
  readOtherPosts = "Read other posts"

  enableSharingButtons = false
  enableReadingTime = true
  enableGlobalLanguageMenu = false
  enableThemeToggle = true

  themeColor = "#1b1c1d"

  customCSS = ["/css/hello-friend-logo.css"]
  customJS = []

  [params.author]
    name = "CC"

  [params.footer]
    trademark = 2026
    rss = true
    copyright = true
    author = false
    topText = []
    bottomText = []

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

[languages]
  [languages.en]
    weight = 1
    title = "CC's Sink"
    copyright = ""

    [languages.en.params]
      subtitle = "A spot for my thoughts, ramblings, and occasionally advice"

      [languages.en.params.logo]
        logoText = "CC's Sink"
        logoHomeLink = "/"

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"

# [[menu.main]]
#   identifier = "about"
#   name = "About"
#   url = "/about/"

# [[menu.main]]
#   identifier = "showcase"
#   name = "Showcase"
#   url = "/showcase/"
