baseURL = "/"
languageCode = "en-us"
title = "CC's Sink"
theme = "PaperMod"
defaultContentLanguage = "en"

enableEmoji = true
enableRobotsTXT = true

[pagination]
pagerSize = 5

[services]
  [services.googleAnalytics]
    id = "G-X0PE3V4L34"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  description = "HeroCC's blog about software engineering, among other things"
  author = "CC"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableThemeToggle = true

  [params.homeInfoParams]
    imageUrl = "https://secure.gravatar.com/avatar/467697c96edf8bb12fd7ab8d84c14cbf?size=200&d=404"
    Title = "CC's Sink"
    Content = "A spot for my thoughts, ramblings, and occasionally advice"

  [[params.socialIcons]]
    name = "X"
    url  = "https://x.com/HeroCC_"

  [[params.socialIcons]]
    name = "github"
    url  = "https://github.com/HeroCC"

  [[params.socialIcons]]
    name = "stackoverflow"
    url  = "https://stackexchange.com/users/1892079"

[languages]
  [languages.en]
    weight = 1
    title = "CC's Sink"
    copyright = "Content CC BY-SA 4.0"

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"

# [[menu.main]]
#   identifier = "about"
#   name = "About"
#   url = "/about/"

# [[menu.main]]
#   identifier = "showcase"
#   name = "Showcase"
#   url = "/showcase/"
